Repository tryber/sd-09-project-recipes-app, pull requests merged in 2021-05, with the labels that each got.

#472 Requisitos Menu principal
  cypress/integration/recipes_list_spec.js
  src/App.css
  src/Components/CocktailCards.js
  src/Components/FoodCards.js
  src/Components/ShowCategories.js
  src/Pages/MainDrink.js
  src/Pages/MainFood.js
  src/services/ApiRequest.js
Labels: Code Review

#487 Group 18 SearchBox
  src/components/FilterButtons/index.js
  src/components/RecipeCard/index.js
  src/components/RecipesList/index.js
  src/components/SearchBar/index.js
  src/context/Provider.js
  src/services/DrinksAPI.js
  src/services/FoodAPI.js
Labels: Code Review

#486 [Grupo 27] Favorite Page 60-66 :rocket:
  package-lock.json
  package.json
  src/components/Details/TitleContainer.jsx
  src/components/Details/index.jsx
  src/components/Header/index.jsx
  src/components/ListFavoriteCards/index.jsx
  src/components/ListFavoriteCards/styled.jsx
  src/components/SearchButtons/index.jsx
  src/components/SearchFilters/index.jsx
  src/context/index.jsx
  src/pages/FavoriteRecipes/index.jsx
  src/pages/Foods/index.jsx
  src/services/localStorage.js
Labels: Code Review

#480 g12-fix-searchBar
  src/components/DrinksCategories.js
  src/components/DrinksComponent.js
  src/components/DrinksRecomendations.js
  src/components/Header.js
  src/components/MealsCategories.js
  src/components/MealsComponent.js
  src/components/MealsRecomendations.js
  src/components/SearchBar.js
  src/context/index.js
Labels: Code Review

#467 Main group 22.req 5
  cypress/integration/login_spec.js
  src/components/LoginForm.js
  src/pages/Login.js
  src/tests/LoginForm.test.js
Labels: Code Review

#449 [Main group 25] Recipes list - Tela principal
  src/App.css
  src/components/CategoryButton/index.js
  src/components/CategoryButton/style.css
  src/components/RecipeCard/index.js
  src/components/SearchBar/index.js
  src/effects/useCategory.js
  src/effects/useResult.js
  src/pages/Drinks.jsx
  src/pages/Food.jsx
  src/pages/Profile.jsx
  src/service/cocktailAPI.js
  src/service/mealAPI.js
Labels: Code Review

#481 [Group 3][Requisitos-10-11-Header]
  src/App.js
  src/Pages/CreatedRecipes.js
  src/Pages/DrinkDetails.js
  src/Pages/Drinks.js
  src/Pages/Explore.js
  src/Pages/ExploreDrinkIngredients.js
  src/Pages/ExploreDrinks.js
  src/Pages/ExploreFoodIngredients.js
  src/Pages/ExploreFoods.js
  src/Pages/ExploreIngredients.js
  src/Pages/ExploreOrigin.js
  src/Pages/FavoriteRecipes.js
  src/Pages/Food.js
  src/Pages/FoodDetails.js
  src/Pages/Profile.js
  src/components/Header.js
  src/styles/Header.css
  src/styles/Profile.css
Labels: Code Review

#390 Main group 9 pagina detalhes
  package-lock.json
  package.json
  src/components/AllRoutes.jsx
  src/components/RecipeCard.jsx
  src/components/RecipeHeader.jsx
  src/components/RecipeIngredients.jsx
  src/components/RecipeInstructions.jsx
  src/effects/useRecipe.js
  src/effects/useRecipeCategories.js
  src/pages/Details.jsx
  src/pages/Drinks.jsx
  src/pages/ExploreDrinkIngredients.jsx
  src/pages/ExploreMealIngredients.jsx
  src/pages/Meals.jsx
  src/pages/RecipeInProgress.jsx
  src/services/APIEndpoints.js
  src/styles/Details.css
  src/styles/RecipeCard.css
  src/styles/RecipeHeader.css
  src/styles/RecipeIngredients.css
  src/tests/Footer.test.js
  src/tests/Login.test.js
  src/tests/Recipes.test.js
  src/tests/renderWithRouter.jsx
  src/tests/renderWithRouterContext.jsx
Labels: Code Review

#513 [GRUPO 3][Main group 3 requisito 47]
  src/App.js
  src/Pages/DoneRecipes.js
  src/Pages/DrinkDetails.js
  src/Pages/DrinkInProgress.js
  src/Pages/FoodDetails.js
  src/Pages/FoodInProgress.js
  src/Pages/InProgress.js
  src/action/ButtonAction.js
  src/components/DrinkCardDetails.js
  src/components/FoodCard.js
  src/components/FoodCardDetails.js
  src/reducers/ButtonReducer.js
  src/styles/Details.css
Labels: Code Review

#529 Requisitos 29 e 31
  src/Components/CocktailCards.js
  src/Components/FoodCards.js
  src/Components/ShowCategories.js
Labels: Code Review

#544 feat: added requirements up to 46
  src/components/DetailsBtnFavoriteRecipe.css
  src/components/DetailsBtnFavoriteRecipe.jsx
  src/components/DetailsBtnShareRecipe.css
  src/components/DetailsBtnShareRecipe.jsx
  src/hooks/useHeartFill.js
Labels: Code Review

#548 Adding toogle logic for the filters.
  src/Redux/actions/actionTypes.js
  src/Redux/actions/index.js
  src/Redux/reducers/filter.js
  src/components/Filter.jsx
  src/components/Filters.jsx
  src/services/fetchRecipes.js
Labels: Code Review

#550 Group 16 - pagina de detalhes finalizada
  package-lock.json
  package.json
  src/components/DetailsDrink.jsx
  src/components/DetailsFood.jsx
  src/components/LikeBtn.jsx
  src/pages/Styles/Details.css
Labels: Code Review

#542 Finaliza tela de receitas prontas
  src/components/AllRoutes.jsx
  src/pages/Details.jsx
  src/pages/DoneRecipes.jsx
  src/pages/RecipesDone.jsx
  src/styles/DoneRecipes.css
Labels: Code Review

#553 css
  package-lock.json
  src/components/Header.jsx
  src/components/RecipeCard.jsx
  src/pages/Drinks.jsx
  src/pages/Explore.jsx
  src/pages/ExploreDrink.jsx
  src/pages/ExploreMeal.jsx
  src/pages/ExploreMealByOrigin.jsx
  src/pages/Login.jsx
  src/pages/Meals.jsx
  src/styles/Explore.css
  src/styles/ExploreIngredients.css
  src/styles/Login.css
  src/styles/RecipeCard.css
Labels: Code Review

#558 Group 16 fixing issues
  src/components/LikeBtn.jsx
Labels: Code Review

#560 tela de login estilizada
  src/App.css
  src/CSS/Login.css
  src/images/cooking.png
  src/images/table-food.jpg
  src/images/table-with-food.jpg
  src/pages/Login.js
Labels: Code Review

#537 Group 10 - Req.67-81
  src/App.js
  src/Provider/Provider.js
  src/components/FoodsList.jsx
  src/components/IngredientCard.jsx
  src/components/RecipeAreasFilters.jsx
  src/components/RecipeCard.jsx
  src/pages/Explore.jsx
  src/pages/ExploreAreas.jsx
  src/pages/ExploreIngredients.jsx
  src/pages/ExploreRecipes.jsx
  src/pages/FoodsMainPage.jsx
  src/pages/NotFound.jsx
Labels: Code Review

#565 [GRUPO 3][Requisito 54 ao 59]
  src/Pages/DoneRecipes.js
  src/Pages/DrinkInProgress.js
  src/Pages/FoodDetails.js
  src/Pages/FoodInProgress.js
  src/components/CardDone.js
  src/components/FoodCardDetails.js
Labels: Code Review

#587 Group 18 share button
  src/components/ShareButton/ShareButton.css
  src/components/ShareButton/index.js
  src/context/Provider.js
Labels: Code Review

#588 g12 requisito 49
  cypress/integration/recipe_in_progress_spec.js
  src/App.css
  src/pages/drinks/DrinksInProgress.js
  src/pages/meals/MealsInProgress.js
Labels: Code Review

#598 Tela de favoritos
  src/pages/FavoriteRecipes.js
  src/pages/drinks/DrinksDetails.js
  src/pages/drinks/DrinksInProgress.js
  src/pages/meals/MealsDetails.js
  src/pages/meals/MealsInProgress.js
  src/services/localStorageService.js
Labels: Code Review

#593 [group 25] tela de explorar ingredientes
  src/components/ExploreIngredients/index.js
  src/components/Footer/index.js
  src/pages/ExploreDrinksIngredients.jsx
  src/pages/ExploreFoodIngredients.jsx
  src/service/cocktailAPI.js
  src/service/mealAPI.js
Labels: Code Review

#610 [FEAT][Requisito 44-45-46][implementacao do botao de favoritos]
  src/components/FavoriteButton/index.js
  src/components/RecomendationCard/index.js
  src/pages/RecipeDetails.js
  src/services/favoriteRecipes.js
Labels: Code Review

#614 Group 16 done recipes
  src/pages/Done.jsx
  src/pages/Login.jsx
  src/pages/Styles/Done.css
Labels: Code Review

#617 Group 16 explore page e explore food and drinks pages req 67 to 74
  src/App.js
  src/pages/Explore.jsx
  src/pages/ExploreBeverages.jsx
  src/pages/ExploreFoods.jsx
Labels: Code Review

#625 [GRUPO 3][Requisito 60 ao 66]
  src/App.js
  src/Pages/DoneRecipes.js
  src/Pages/FavoriteRecipes.js
  src/components/CardFavorite.js
Labels: Code Review

#629 Group 8 feat recipes done screen
  src/App.js
  src/components/DetailsBtnFavoriteRecipe.jsx
  src/components/DetailsBtnStartRecipe.jsx
  src/components/RecipesDoneCards.jsx
  src/components/RecomendedRecipes.jsx
  src/pages/RecipeDetails.jsx
  src/pages/RecipesDone.css
  src/pages/RecipesDone.jsx
Labels: Code Review

#628 [Group-6][Tests] - MainPages and SearchBar
  .eslintrc.json
  .github/workflows/main.yml
  README.md
  cypress/mocks/goatMeals.js
  package-lock.json
  package.json
  src/components/SearchBar.jsx
  src/context/RecipesAppProvider.jsx
  src/pages/MainDrinks.jsx
  src/pages/MainFoods.jsx
  src/services/CocktailApi.js
  src/services/MealApi.js
  src/tests/MainDrinks.test.js
  src/tests/MainFoods.test.js
  src/tests/SearchBar.test.js
  src/tests/mocks/index.js
Labels: Code Review

#637 [GRUPO 3][Requisitos 79 ao 81]
  src/App.js
  src/Pages/DoneRecipes.js
  src/Pages/ExploreOrigin.js
  src/Pages/NotFound.js
  src/action/FoodAndDrinkAction.js
  src/action/OriginAction.js
  src/reducers/FoodAndDrinkReducer.js
  src/reducers/OriginReducer.js
  src/reducers/index.js
  src/styles/NotFound.css
Labels: Code Review

#611 Estilizando pagina de receitas
  src/App.css
  src/CSS/ComidasBebidas.css
  src/CSS/Footer.css
  src/CSS/Header.css
  src/CSS/Login.css
  src/CSS/Paleta.css
  src/components/Footer.js
  src/components/Header.js
  src/pages/Bebidas.js
  src/pages/Comidas.js
Labels: Code Review

#592 Main group 34 req 81
  src/App.js
  src/components/Explorer.js
  src/components/Header.js
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/pages/Explorar.js
  src/pages/ExplorarBebidas.js
  src/pages/ExplorarComidas.js
  src/pages/ExplorarIngredientes.js
  src/pages/ExplorarOrigem.js
  src/pages/NotFound.js
  src/pages/Perfil.js
  src/pages/ReceitasFavoritas.js
  src/pages/ReceitasFeitas.js
  src/services/api.js
  xdc
Labels: Code Review

#595 [Group 34] Tests - Footer e App
  src/App.test.js
  src/tests/Footer.test.js
Labels: Code Review

#639 [Group 25] Tela de explorar bebidas ou comidas
  src/App.css
  src/components/ExploreDrinksOrFoods/index.js
  src/components/Recommendations/index.js
  src/components/Recommendations/style.css
  src/pages/DrinkRecipe.jsx
  src/pages/FoodRecipe.jsx
  src/service/cocktailAPI.js
  src/service/mealAPI.js
Labels: Code Review

#647 [Main group 18][feat][requirement 47, 48, 49]
  src/components/StartRecipeButton/index.js
  src/pages/RecipeInProgress.js
Labels: Code Review

#654 [Main group 25] Done recipes & Favorite recipes
  src/App.css
  src/components/Header/index.js
  src/components/HorizontalCard/index.js
  src/components/HorizontalCard/style.css
  src/components/SearchBar/index.js
  src/images/recipe.svg
  src/pages/DoneRecipes.jsx
  src/pages/Drinks.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/Login.jsx
  src/pages/Profile.jsx
  src/service/mealAPI.js
Labels: Code Review

#670 Group 16 favorite recipes page, requisitos 60 a 66
  src/pages/Done.jsx
  src/pages/Favorites.jsx
  src/pages/Styles/Favorites.css
Labels: Code Review

#674 Style lint
  src/pages/Styles/Favorites.css
Labels: Code Review

#669 Group 16 profile
  cypress/integration/profile_spec.js
  src/pages/Login.jsx
  src/pages/Profile.jsx
  src/pages/Styles/Login.css
  src/pages/Styles/Profile.css
Labels: Code Review

#675 Arrumando erros de lint.
  src/pages/Done.jsx
Labels: Code Review

#646 Conserta erros de logica no componente RecipeIngredients | Cria um co…
  src/App.jsx
  src/components/RecipeIngredients.jsx
  src/components/Recomendations.jsx
  src/pages/Details.jsx
  src/pages/RecipeInProgress.jsx
Labels: Code Review, help wanted

#679 Group 16 fix footer
  src/pages/Done.jsx
  src/pages/Profile.jsx
Labels: Code Review

#681 [FEAT][GROUP 28][TELA PRINCIPAL]
  src/App.css
  src/components/MainCards.jsx
  src/components/buttons/categories/CategoriesBtn.jsx
Labels: Code Review

#683 [FIX][GROUP 28][TELA PRINCIPAL]
  src/App.css
Labels: Code Review

#659 [FEAT][Requisito 77][Redireciona usuário ao clicar em um ingrediente]
  src/components/Ingredients/Index.js
Labels: Code Review

#707 [FEAT][Requisito 55-56][O card possui os atributos corretos]
  src/components/CardRecipe/index.js
  src/components/FilterRecipes/index.js
  src/components/ShareButton/index.js
  src/hooks/useFilterType.js
  src/pages/CompletedRecipes.js
  src/pages/DoneRecipes.js
  src/pages/Routes.js
Labels: Code Review

#652 Add favorite recipes page
  package-lock.json
  src/pages/FavoriteRecipes.jsx
Labels: Code Review

#697 [GRUPO 3][Requisito 13 ao 18]
  src/App.js
  src/Pages/DoneRecipes.js
  src/Pages/Drinks.js
  src/Pages/ExploreDrinkIngredients.js
  src/Pages/ExploreFoodIngredients.js
  src/Pages/ExploreOrigin.js
  src/Pages/FavoriteRecipes.js
  src/Pages/Food.js
  src/Pages/FoodInProgress.js
  src/Pages/Login.js
  src/Pages/NotFound.js
  src/Pages/Profile.js
  src/action/FoodAndDrinkAction.js
  src/action/OriginAction.js
  src/components/Header.js
  src/components/SearchBar.js
  src/reducers/FoodAndDrinkReducer.js
  src/reducers/OriginReducer.js
  src/reducers/index.js
  src/styles/App.css
  src/styles/Details.css
  src/styles/DoneRecipes.css
  src/styles/Geral.css
  src/styles/Header.css
  src/styles/InProgress.css
  src/styles/Login.css
  src/styles/NotFound.css
  src/styles/Profile.css
  src/styles/mainScreen.css
Labels: Code Review

#709 [FEAT][Requisito 59][Redirecione para a tela de detalhes da receita]
  src/components/CardRecipe/index.js
Labels: Code Review

#714 Group 18 share button refactor
  src/components/CardRecipe/index.js
  src/components/ShareButton/index.js
  src/pages/RecipeDetails.js
Labels: Code Review

#702 [grupo 27] doneRecipe | add doneRecipe page
  src/components/Details/TitleContainer.jsx
  src/components/Details/index.jsx
  src/components/ListDoneRecipeCard/index.jsx
  src/components/ListDoneRecipeCard/styled.jsx
  src/components/ListFavoriteCards/index.jsx
  src/components/ListIngredientsCards/index.jsx
  src/components/ListIngredientsCards/styled.jsx
  src/components/SearchButtons/index.jsx
  src/context/index.jsx
  src/pages/DoneRecipes/index.jsx
  src/pages/FavoriteRecipes/index.jsx
  src/services/localStorage.js
Labels: Code Review

#711 [FIX][GROUP 28][CSS]
  src/App.css
  src/components/buttons/categories/CategoriesBtn.jsx
Labels: Code Review

#717 feat: added requirements 67 up to 69 explore screen
  src/App.js
  src/pages/Explore.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreMeals.jsx
Labels: Code Review

#716 [Main group 18][feat][requirement 50]
  src/pages/ExploreArea.js
  src/pages/RecipeInProgress.css
  src/pages/RecipeInProgress.js
Labels: Code Review

#590 [Group 8] In Progress Page
  .gitignore
  src/App.css
  src/App.js
  src/components/in-progress/DetailsBtnFinishRecipeInProgress.jsx
  src/components/in-progress/InProgressHeaderDetails.jsx
  src/components/in-progress/IngredientsInProgress.jsx
  src/pages/InProgress.css
  src/pages/InProgress.jsx
Labels: Code Review

#720 feat: added requirements 70-74 exploredrinksandmeals screens
  src/App.js
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreIngredients.jsx
  src/pages/ExploreMeals.jsx
  src/pages/ExploreOrigin.jsx
Labels: Code Review

#727 [FEAT][Requisitos 63, 65, 66][Implementa parte da lógica da favorite page]
  src/components/CardRecipe/index.js
  src/components/FavoriteButton/index.js
  src/pages/FavoriteRecipes.js
Labels: Code Review

#382 [GRUPO 13] Tela Principal de Receitas
  src/App.js
  src/components/RecipeCard.jsx
  src/pages/CocktailRecipes.jsx
  src/pages/Login.jsx
  src/pages/MealRecipes.jsx
Labels: Code Review

#744 fix: issues with routes
  src/App.js
Labels: Code Review

#732 Group 16 explore by area
  cypress/integration/profile_spec.js
  src/App.js
  src/components/NotFound.jsx
  src/pages/Areas.jsx
  src/pages/Styles/Areas.css
  src/services/fetchAreas.js
Labels: Code Review

#620 [GRUPO 01] [TELA DE RECEITAS EM PROGRESSO]
  src/components/Providers/LoginProvider.jsx
  src/components/Providers/RecipesProvider.jsx
  src/components/Router.jsx
  src/components/ShareButton.jsx
  src/pages/EmProcesso.jsx
  src/styles/InProgress.css
Labels: In Development

#755 Group 16 explore by ingredients, req 75, 76 e 77
  src/Redux/actions/actionTypes.js
  src/Redux/actions/index.js
  src/Redux/reducers/recipesList.js
  src/pages/Beverages.jsx
  src/pages/Foods.jsx
  src/pages/Ingredients.jsx
  src/pages/Styles/Details.css
  src/pages/Styles/Recipes.css
  src/services/fetchIngredients.js
Labels: Code Review

#738 [GRUPO - 25] TELA DE EXPLORAR POR AREA
  src/App.js
  src/components/ExploreArea/index.js
  src/components/ExploreFoodAreaa/index.js
  src/components/NotFound/index.js
  src/pages/ExploreFoodArea.jsx
Labels: Code Review

#488 [Grupo 2] (feat) Adiciona requisitos 15 a 18
  src/components/Card.js
  src/components/Loading.js
  src/components/SearchBar.js
  src/pages/Main.js
  src/redux/actions/recipes.js
  src/redux/reducers/recipes.js
  src/redux/reducers/search.js
  src/redux/types/index.js
  src/services/api.js
Labels: Code Review

#780 poagina de bebidas estilizada
  src/CSS/ComidasBebidas.css
  src/pages/Bebidas.js
Labels: Code Review

#778 Main group 34 req40
  src/components/ButtonStartOrContinueRecipe.js
  src/components/RecipeCard.js
  src/components/RecipeDetailsCard.js
  src/components/RecomedationsList.js
  src/components/RecomendationsList.js/index.js
  src/components/ShareRecipeButton/style.css
  src/pages/Comidas.js
Labels: Code Review

#752 [Grupo 2] (RecipeList) Adiciona requisitos 54 a 66
  package-lock.json
  package.json
  src/App.css
  src/components/Image.js
  src/components/RecipeListCard.js
  src/pages/RecipeList.js
  src/services/api.js
  src/services/storage.js
Labels: Code Review

#785 [FIX][GROUP 28][TELA DE DETALHES]
  src/context/provider.js
  src/pages/FoodDetails.jsx
Labels: Code Review

#788 G10/req.54 59
  src/App.js
  src/Provider/Provider.js
  src/components/DoneRecipesCard.jsx
  src/components/DoneRecipesFilters.jsx
  src/pages/DoneRecipes.jsx
  src/pages/DrinkDetails.jsx
  src/pages/MealDetails.jsx
Labels: Code Review

#795 Main group 16 feat tela inprogress
  src/App.js
  src/components/DrinkInProgress.jsx
  src/components/FoodInProgress.jsx
  src/pages/Done.jsx
  src/pages/Styles/Details.css
Labels: Code Review

#817 [FEAT][GROUP 28][TELA DE RECEITAS FAVORITAS]
  src/components/RecipesCards.jsx
  src/pages/FavoriteRecipes.jsx
Labels: Code Review

#813 [Grupo 2] (fix/refac) Corrige requisitos 57 e 63 e refatora componentes
  src/components/CopyMsg.js
  src/components/RecipeListCard.js
  src/components/ShareButton.js
  src/pages/RecipeList.js
  src/services/api.js
  src/services/getPath.js
Labels: Code Review

#835 Media queries
  src/CSS/ComidasBebidas.css
  src/CSS/DetalhesProgresso.css
  src/CSS/DoneCard.css
  src/CSS/ExplorarComidas.css
  src/CSS/ExplorarComidasIngredientes.css
  src/CSS/ExplorarComidasOrigem.css
  src/CSS/Login.css
  src/pages/ExplorarBebidasIngredientes.js
  src/pages/ExplorarComidasArea.js
  src/pages/ExplorarComidasIngredientes.js
Labels: Code Review

#839 [FET][GROUP 28][TELA-DE-RECEITAS-FAVORITAS]
  src/components/RecipesCards.jsx
Labels: Code Review

#826 [FEAT] - explore details
  src/App.jsx
  src/components/ExploreButtons.jsx
  src/pages/ExploreDrinksByIngredients.jsx
  src/pages/ExploreFoodsByIngredients.jsx
  src/pages/ExploreFoodsByOrigin.jsx
  src/pages/NotFound.jsx
  src/pages/index.js
  src/services/CocktailApi.js
  src/services/MealApi.js
Labels: Code Review

#840 [Group-6][Feat] - Recipes in Progress
  src/components/RecipeDetailsHeader.jsx
  src/components/RecipeFavoriteButton.jsx
  src/components/RecipeIngredients.jsx
  src/components/RecipeIngredientsList.jsx
  src/components/RecipeInstructions.jsx
  src/components/RecipeShareButton.jsx
  src/components/RecipeStartButton.jsx
  src/pages/DrinkDetails.jsx
  src/pages/DrinkInProgress.jsx
  src/pages/RecipeDetails.jsx
  src/pages/RecipeInProgress.jsx
  src/styles/components/RecipeIngredients.css
Labels: Code Review

#846 [Group-6][Feat] - Done Recipes
  src/pages/DoneRecipes.jsx
  src/pages/DrinkInProgress.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/RecipeInProgress.jsx
  src/styles/FavoriteRecipes.css
  src/styles/pages/DoneRecipes.css
  src/styles/pages/InProgress.css
Labels: Code Review

#852 [FEAT][GROUP 28][EXPLORE BY AREA]
  src/components/RecipesCards.jsx
  src/components/RecipesList.jsx
  src/pages/DrinkDetails.jsx
  src/pages/DrinkInProgress.jsx
  src/pages/ExploreDrinksIngredients.jsx
  src/pages/ExploreFoodsArea.jsx
  src/pages/ExploreFoodsIngredients.jsx
  src/pages/FoodDetails.jsx
  src/pages/FoodInProgress.jsx
  src/pages/Login.jsx
Labels: Code Review

#856 [GRUPO 03][Requisito 01]
  .eslintignore
  .github/workflows/main.yml
  cypress/mocks/goatMeals.js
  package-lock.json
  package.json
  src/App.test.js
  src/Pages/DrinkDetails.js
  src/Pages/ExploreDrinkIngredients.js
  src/Pages/ExploreDrinks.js
  src/Pages/ExploreFoodIngredients.js
  src/Pages/FoodDetails.js
  src/Pages/FoodInProgress.js
  src/Pages/Profile.js
  src/action/ButtonAction.js
  src/action/FoodAndDrinkAction.js
  src/action/OriginAction.js
  src/components/CardDone.js
  src/components/CardFavorite.js
  src/components/CarouselDrinkDetails.js
  src/components/Header.js
  src/mocks/areas.js
  src/mocks/drinkCategories.js
  src/mocks/drinkIngredients.js
  src/mocks/drinks.js
  src/mocks/drinksByIngredient.js
  src/mocks/goatMeals.js
  src/mocks/italianMeals.js
  src/mocks/mealCategories.js
  src/mocks/mealIngredients.js
  src/mocks/meals.js
  src/mocks/mealsByIngredient.js
  src/mocks/oneDrink.js
  src/mocks/oneMeal.js
  src/mocks/ordinaryDrinks.js
  src/reducers/OriginReducer.js
  src/styles/Details.css
  src/tests/App.test.js
  src/tests/DoneRecipes.test.js
  src/tests/Drink.test.js
  src/tests/DrinkDetails.test.js
  src/tests/DrinksInProgress.test.js
  src/tests/Explore.test.js
  src/tests/ExploreDrinkIngredients.test.js
  src/tests/ExploreDrinks.test.js
  src/tests/ExploreFood.test.js
  src/tests/ExploreFoodArea.test.js
  src/tests/ExploreFoodIngredients.test.js
  src/tests/FavoriteRecipes.test.js
  src/tests/Food.test.js
  src/tests/FoodDetails.test.js
  src/tests/FoodInProgress.test.js
  src/tests/Login.test.js
  src/tests/NotFound.test.js
  src/tests/Profile.test.js
  src/tests/testRender.js
Labels: Code Review

#869 Group 16 loading
  src/App.css
  src/Redux/actions/actionTypes.js
  src/Redux/actions/index.js
  src/Redux/reducers/recipesList.js
  src/components/ChefLoading.jsx
  src/components/Header.jsx
  src/components/Loading.jsx
  src/images/chef-animation.gif
  src/pages/Beverages.jsx
  src/pages/Foods.jsx
Labels: Code Review
