Repository tryber/sd-09-project-recipes-app, pull requests merged in 2021-04, with the labels that each got.

#23 initial structure
  PADROES.txt
  README.md
  package-lock.json
  package.json
  src/components/index.js
  src/context/index.js
  src/index.js
  src/pages/index.js
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/store/index.js
  src/services/index.js
  src/tests/utils/index.js
Labels: Code Review

#32 Grupo 01 - feat / Router
  package-lock.json
  src/App.js
  src/components/Loading.jsx
  src/index.js
  src/pages/Detalhes.jsx
  src/pages/EmProcesso.jsx
  src/pages/Explorar.jsx
  src/pages/ExplorarArea.jsx
  src/pages/ExplorarIngredientes.jsx
  src/pages/ExplorarTipo.jsx
  src/pages/Login.jsx
  src/pages/Perfil.jsx
  src/pages/ReceitasLista.jsx
  src/pages/ReceitasPrincipal.jsx
Labels: Code Review

#49 [GRUPO 3][requisito-2-ao-8]
  package-lock.json
  package.json
  src/App.js
  src/components/Login.js
Labels: Code Review

#40 [GRUPO 26] Tela de login concluída
  package-lock.json
  src/App.js
  src/Pages/Login.jsx
Labels: Code Review

#56 Add Login Page and Provider structure
  package-lock.json
  src/App.js
  src/Provider/Provider.js
  src/Provider/RecipesContext.js
  src/index.js
  src/pages/Login.jsx
Labels: Code Review

#66 Requisito 3-4
  src/pages/Login.js
Labels: Code Review

#53 [Grupo 12] - Criação da estrutura inicial header e login
  package-lock.json
  src/App.js
  src/components/Header.js
  src/components/index.js
  src/index.js
  src/pages/Cocktails.js
  src/pages/Details.js
  src/pages/Explore.js
  src/pages/Login.js
  src/pages/Meals.js
  src/pages/Profile.js
  src/pages/index.js
  src/services/api.js
Labels: Code Review

#45 Grupo 9 - Requisitos 9 10 11
  package-lock.json
  src/App.css
  src/App.jsx
  src/components/Header.jsx
  src/pages/Drinks.jsx
  src/pages/Explore.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreDrinksIngredients.jsx
  src/pages/ExploreFoodByOrigin.jsx
  src/pages/ExploreFoods.jsx
  src/pages/ExploreFoodsIngredients.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/Foods.jsx
  src/pages/Profile.jsx
  src/pages/RecipesDone.jsx
  src/styles/Header.css
Labels: Code Review

#80 [GRUPO 3][Requisito 27 ao 32]
  src/App.js
  src/Pages/Drinks.js
  src/Pages/Food.js
  src/action/FoodAndDrinkAction.js
  src/components/DrinkCard.js
  src/components/DrinkDetails.js
  src/components/FoodCard.js
  src/components/FoodDetails.js
  src/reducers/FoodAndDrinkReducer.js
Labels: Code Review

#71 Add validation function to login page
  src/App.js
  src/pages/Login.jsx
Labels: Code Review

#14 [GROUP 26] - [Header]
  package-lock.json
  src/App.js
  src/components/ComplementHeader.jsx
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/index.js
  src/pages/Bebidas.jsx
  src/pages/BebidasPorIngredientes.jsx
  src/pages/ComidaOrigem.jsx
  src/pages/Comidas.jsx
  src/pages/ComidasPorIngredientes.jsx
  src/pages/Explorar.jsx
  src/pages/ExplorarBebidas.jsx
  src/pages/ExplorarComidas.jsx
  src/pages/Login.jsx
  src/pages/Perfil.jsx
  src/pages/ReceitasFavoritas.jsx
  src/pages/ReceitasFeitas.jsx
  src/styles/Header.css
Labels: Under Development

#107 [Grupo 2] Create app's directories initial structure
  package-lock.json
  src/components/Card.js
  src/components/Header.js
  src/hooks/index.js
  src/pages/Login.js
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/redux/types/index.js
  src/services/api.js
  src/services/storage.js
Labels: Code Review

#99 Create Routes & change favicon
  package-lock.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/recipe.svg
  src/App.js
  src/index.js
  src/pages/DoneRecipes.jsx
  src/pages/DrinkRecipe.jsx
  src/pages/DrinkRecipeProgress.jsx
  src/pages/Drinks.jsx
  src/pages/Explore.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreDrinksIngredients.jsx
  src/pages/ExploreFood.jsx
  src/pages/ExploreFoodArea.jsx
  src/pages/ExploreFoodIngredients.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/Food.jsx
  src/pages/FoodRecipe.jsx
  src/pages/FoodRecipeProgress.jsx
  src/pages/Login.jsx
  src/pages/Profile.jsx
Labels: Code Review

#108 [FEAT][Requisito 00 Estrutura][criaçao de rotas]
  src/App.js
  src/pages/CompletedRecipes.js
  src/pages/Drinks.js
  src/pages/ExploreArea.js
  src/pages/ExploreDrinks.js
  src/pages/ExploreFood.js
  src/pages/Explorer.js
  src/pages/FavoriteRecipes.js
  src/pages/Food.js
  src/pages/Ingredients.js
  src/pages/Login.js
  src/pages/NotFound.js
  src/pages/Profile.js
  src/pages/RecipeInProgress.js
  src/pages/Recipes.js
  src/pages/Routes.js
  src/pages/index.js
Labels: Code Review

#121 [Grupo-2] Configuração inicial do Redux
  package-lock.json
  package.json
  src/redux/reducers/index.js
  src/redux/store/index.js
Labels: Code Review

#85 Requisitos 12 e 13 feitos
  package-lock.json
  src/Components/Header.js
  src/Components/Header/index.js
  src/Components/SearchBar.js
  src/Components/styles/Header.css
  src/Components/styles/SearchBar.css
  src/Pages/MainDrink.js
  src/Pages/MainFood.js
  src/Pages/Profile.js
  src/Styles/Profile.css
Labels: Code Review

#128 [Group 9][Profile page]
  src/pages/Profile.jsx
  src/styles/Profile.css
Labels: Code Review

#131 Requisito 5
  src/pages/Login.js
Labels: Code Review

#122 Fix - Requisito 20
  src/components/Footer.css
  src/components/Footer.js
  src/pages/DoneRecipes.js
  src/pages/FavoriteRecipes.js
Labels: Code Review

#137 Add local storage items and redirect on button click
  src/pages/Login.jsx
Labels: Code Review

#138 g12-fix-header
  src/components/Header.js
  src/components/SearchBar.js
  src/pages/Details.js
  src/pages/Drinks.js
  src/pages/ExploreDrinks.js
  src/pages/ExploreMeals.js
  src/pages/Meals.js
  src/pages/Profile.js
Labels: Code Review

#16 [Grupo 26][Search bar] - PROJECT INITIATED
  package-lock.json
  package.json
  src/App.js
  src/actions/index.js
  src/components/Header.jsx
  src/components/Loading.jsx
  src/components/Recipes.jsx
  src/components/SearchBar.jsx
  src/contexts/RecipesContext.js
  src/contexts/RecipesProvider.js
  src/index.js
  src/pages/Bebidas.jsx
  src/pages/BebidasPorIngredientes.jsx
  src/pages/Cocktails.jsx
  src/pages/ComidaOrigem.jsx
  src/pages/Comidas.jsx
  src/pages/ComidasPorIngredientes.jsx
  src/pages/Explorar.jsx
  src/pages/ExplorarBebidas.jsx
  src/pages/ExplorarComidas.jsx
  src/pages/Meals.jsx
  src/pages/Perfil.jsx
  src/pages/ReceitasFavoritas.jsx
  src/pages/ReceitasFeitas.jsx
  src/reducers/index.js
  src/reducers/recipes.js
  src/services/fetchRecipesData.js
  src/store/index.js
Labels: Under Development

#154 requisitos 6 ao 8 feitos
  src/pages/Login.js
Labels: Code Review

#47 Group 8 bottom navigation
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/BottomNav.css
  src/components/BottomNav.jsx
  src/pages/Login.jsx
  src/tests/bottomNav.test.js
  src/tests/renderWithRouter.js
Labels: Code Review

#142 implements explore page features
  src/pages/Explore.jsx
  src/styles/Explore.css
Labels: Code Review

#190 Group 16 header
  src/App.js
  src/Redux/actions/actionTypes.js
  src/Redux/actions/index.js
  src/Redux/reducers/index.js
  src/Redux/reducers/searchBar.js
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/pages/Areas.jsx
  src/pages/Beverages.jsx
  src/pages/Explore.jsx
  src/pages/ExploreBeverages.jsx
  src/pages/ExploreFoods.jsx
  src/pages/Foods.jsx
Labels: Code Review

#192 Correçao uso do effect
  src/Components/CocktailCards.js
  src/Components/FoodCards.js
Labels: Code Review

#215 [Grupo 12] - Requisitos 13 - 18
  src/components/DrinksComponent.js
  src/components/Header.js
  src/components/MealsComponent.js
  src/components/SearchBar.js
  src/services/api.js
Labels: Code Review

#153 feat.Login.test.js
  src/pages/Login.js
  src/tests/Login.test.js
  src/tests/renderWithRouter.js
Labels: Code Review

#198 [GRUPO 3][Requisito 33 ao 37]
  src/Pages/Drinks.js
  src/Pages/Food.js
  src/action/FoodAndDrinkAction.js
  src/action/FoodAndDrinkDetailsAction.js
  src/components/CarouselDrinkDetails.js
  src/components/CarouselFoodDetails.js
  src/components/DrinkCard.js
  src/components/DrinkDetails.js
  src/components/FoodCard.js
  src/components/FoodDetails.js
  src/css/Details.css
  src/reducers/FoodAndDrinkDetailsReducer.js
  src/reducers/index.js
Labels: Code Review

#204 Página de Login
  .eslintignore
  .stylelintignore
  src/App.js
  src/pages/Login.jsx
Labels: Code Review

#187 feature 33
  .eslintrc.json
  README.md
  src/actions/MealById.js
  src/actions/getDrinkById.js
  src/pages/DrinkDetails.jsx
  src/pages/FoodDetails.jsx
  src/reducers/data.js
  src/services/fetchDrinkById.js
  src/services/fetchMealById.js
Labels: Code Review

#211 [Group-6] Feature - SearchBar
  src/App.jsx
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/context/MyContext.js
  src/context/Provider.js
  src/context/RecipesAppContext.jsx
  src/context/RecipesAppProvider.jsx
  src/pages/MainDrinks.jsx
  src/pages/MainFoods.jsx
  src/services/CocktailApi.js
  src/services/MealApi.js
  src/styles/MainDrinks.css
  src/styles/MainFoods.css
  src/styles/SearchBar.css
  src/tests/Header.test.js
Labels: Code Review

#225 [GROUP 26] - [Feats Css]
  src/components/Header.jsx
  src/components/Recipes.jsx
  src/components/SearchBar.jsx
  src/styles/Header.css
  src/styles/Recipes.css
Labels: Code Review

#179 feat: incluindo elementos na tela de login(tested)
  cypress/integration/login_spec.js
  src/Pages/Login.js
  src/components/LoginForm.js
  src/tests/LoginForm.test.js
Labels: Code Review

#193 [Main group 25] requirement 13, 14 & 15
  .eslintrc.json
  README.md
  src/App.css
  src/components/SearchBar.jsx
  src/pages/Drinks.jsx
  src/pages/Food.jsx
Labels: Code Review

#232 [FEAT][Requisitos 19-24][Implementa componente Menu]
  src/components/Header/Header.css
  src/components/Header/index.js
  src/components/Menu.js
  src/components/Menu/Menu.css
  src/components/Menu/index.js
  src/components/SearchBar/index.js
  src/pages/Drinks.js
  src/pages/ExploreArea.js
  src/pages/ExploreDrinks.js
  src/pages/ExploreFood.js
  src/pages/Explorer.js
  src/pages/Food.js
  src/pages/Ingredients.js
  src/pages/Profile.js
Labels: Code Review

#216 Group 16 requirements 25 26
  src/App.js
  src/Redux/actions/actionTypes.js
  src/Redux/actions/index.js
  src/Redux/reducers/index.js
  src/Redux/reducers/recipesList.js
  src/components/Card.jsx
  src/components/Footer.css
  src/components/Footer.jsx
  src/components/Header.jsx
  src/pages/Beverages.jsx
  src/pages/Foods.jsx
  src/pages/Recipes.jsx
  src/pages/Styles/Recipes.css
  src/services/fetchRecipes.js
Labels: Code Review

#262 Group 16 req 13 ao 18
  src/App.css
  src/App.js
  src/Redux/actions/actionTypes.js
  src/Redux/actions/index.js
  src/Redux/reducers/index.js
  src/Redux/reducers/recipesList.js
  src/Redux/reducers/searchBar.js
  src/components/Card.css
  src/components/Card.jsx
  src/components/Cards.css
  src/components/Cards.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Loading.jsx
  src/components/SearchBar.css
  src/components/SearchBar.jsx
  src/pages/Beverages.jsx
  src/pages/Foods.jsx
  src/services/index.js
Labels: Code Review

#251 refactor: changed and bug fix on searchbar component
  src/components/SearchBar.jsx
  src/context/MealsAndDrinkProvider.js
  src/services/api.js
  src/tests/header.test.js
Labels: Code Review

#272 G10/req.25-32
  src/App.js
  src/Provider/Provider.js
  src/components/DrinksList.jsx
  src/components/FoodsList.jsx
  src/components/RecipeCard.jsx
  src/components/RecipeCategoriesFilters.jsx
  src/pages/DrinksMainPage.jsx
  src/pages/Foods.jsx
  src/pages/FoodsMainPage.jsx
Labels: Code Review

#267 [Group-6] Tests
  src/components/Header.jsx
  src/pages/Login.jsx
  src/tests/Header.test.js
  src/tests/Profile.test.js
  src/tests/helpers/renderWithRouter.js
Labels: Code Review

#282 [Grupo 12] - Details part 1
  src/App.js
  src/pages/Details.js
  src/pages/DrinksDetails.js
  src/pages/MealsDetails.js
  src/pages/Profile.js
  src/pages/index.js
  src/services/api.js
Labels: Code Review

#293 [Grupo 16] Tela de Login
  src/App.js
  src/pages/Login.jsx
Labels: Code Review

#288 [GRUPO 3][Requisito 38 ao 42]
  src/App.js
  src/Pages/InProgress.js
  src/action/ButtonAction.js
  src/components/CarouselDrinkDetails.js
  src/components/CarouselFoodDetails.js
  src/components/DrinkDetails.js
  src/components/FoodDetails.js
  src/css/Details.css
  src/reducers/ButtonReducer.js
  src/reducers/index.js
Labels: Code Review

#296 Add Profile page
  src/App.js
  src/pages/Profile.jsx
Labels: Code Review

#304 [Grupo 12] - Corriginto o redirect da categoria Goat
  src/components/DrinksComponent.js
  src/components/MealsComponent.js
  src/components/SearchBar.js
  src/context/Context.js
Labels: Code Review

#295 [FEAT][Requisitos 25-31][Implementa tela principal de receitas]
  .github/workflows/main.yml
  cypress/mocks/goatMeals.js
  src/components/FilterButtons/index.js
  src/components/RecipeCard/RecipeCard.css
  src/components/RecipeCard/index.js
  src/pages/Drinks.js
  src/pages/Food.js
  src/services/DrinksAPI.js
  src/services/FoodAPI.js
  src/services/index.js
Labels: Code Review

#294 Group 16 requirement 27
  src/components/Card.css
  src/components/Cards.css
  src/components/Cards.jsx
  src/components/Filter.jsx
  src/components/Filters.jsx
  src/components/Header.jsx
  src/components/SearchBar.css
  src/pages/Beverages.jsx
  src/pages/Foods.jsx
Labels: In Development

#317 [Group-6][Feat] - Main-Page
  src/components/Header.jsx
  src/context/RecipesAppProvider.jsx
  src/pages/MainDrinks.jsx
  src/pages/MainFoods.jsx
  src/pages/Profile.jsx
  src/services/CocktailApi.js
  src/services/MealApi.js
  src/styles/Header.css
  src/styles/MainDrinks.css
  src/styles/MainFoods.css
  src/styles/MainPage.css
  src/styles/SearchBar.css
  src/styles/bottomMenu.css
Labels: Code Review

#283 [GRUPO 25] HEADER
  package-lock.json
  package.json
  src/App.js
  src/components/Header/index.js
  src/components/Header/style.css
  src/pages/DoneRecipes.jsx
  src/pages/Drinks.jsx
  src/pages/Explore.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreDrinksIngredients.jsx
  src/pages/ExploreFood.jsx
  src/pages/ExploreFoodArea.jsx
  src/pages/ExploreFoodIngredients.jsx
  src/pages/FavoriteRecipes.jsx
  src/pages/Food.jsx
  src/pages/Profile.jsx
Labels: Code Review

#316 Main group 34 reqs 14 e 15
  cypress/integration/header_spec.js
  src/App.js
  src/components/SearchBar.js
  src/pages/Bebidas.js
  src/pages/Comidas.js
  src/pages/Comidas/SearchBar.js
  src/pages/Comidas/index.js
  src/pages/Header.js
  src/pages/Login.js
  src/services/apiDrinks.js
  src/services/apiMeals.js
Labels: Code Review

#284 [Grupo 2] feat(Header): Adiciona requisitos 9 e 10
  src/App.js
  src/components/Header.js
  src/pages/Explore.js
  src/pages/Main.js
  src/pages/Profile.js
  src/pages/RecipeDetails.js
  src/pages/RecipeList.js
  src/pages/RecipeProgress.js
  src/routes/index.js
  src/services/pageTitles.js
Labels: Code Review

#332 Requisito 27
  src/Components/ShowCategories.js
  src/Components/styles/Footer.css
  src/Pages/MainDrink.js
Labels: Code Review

#351 G10/req.47
  src/App.js
  src/pages/RecipeInProgress.jsx
Labels: Code Review

#340 [Main group 25] SearchBar
  src/App.css
  src/components/Header/index.js
  src/components/RecipeCard/index.js
  src/components/RecipeCard/style.css
  src/components/SearchBar/index.js
  src/components/SearchBar/style.css
  src/pages/Drinks.jsx
  src/pages/ExploreFoodArea.jsx
  src/pages/Food.jsx
Labels: Code Review

#348 [Main group 25] Footer
  package-lock.json
  package.json
  src/components/Footer/index.js
  src/components/Footer/style.css
  src/components/Header/index.js
  src/components/Header/style.css
  src/pages/Drinks.jsx
  src/pages/Explore.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreDrinksIngredients.jsx
  src/pages/ExploreFood.jsx
  src/pages/ExploreFoodArea.jsx
  src/pages/ExploreFoodIngredients.jsx
  src/pages/Food.jsx
  src/pages/Profile.jsx
Labels: Code Review

#373 Requisito tela de receitas feitas MOCK
  src/pages/ReceitasFeitas.js
Labels: Code Review

#381 [FEAT][GROUP 28][SearchBar]
  src/components/SearchBar.jsx
  src/context/provider.js
  src/services/index.js
Labels: Code Review

#307 req 35
  src/pages/DrinkDetails.jsx
  src/pages/FoodDetails.jsx
Labels: Code Review

#383 Group 16 requirement 27
  src/Redux/actions/actionTypes.js
  src/Redux/actions/index.js
  src/Redux/reducers/couldRedirect.js
  src/Redux/reducers/index.js
  src/Redux/reducers/recipesList.js
  src/components/Card.jsx
  src/components/Cards.jsx
  src/components/Filter.jsx
  src/components/Filters.jsx
  src/components/SearchBar.jsx
  src/pages/Beverages.jsx
  src/pages/Details.jsx
  src/pages/Foods.jsx
  src/pages/Recipes.jsx
  src/services/fetchCategories.js
  src/services/fetchRecipes.js
Labels: Code Review

#394 [Grupo 9][ Meals by area page]
  src/components/AllRoutes.jsx
  src/pages/ExploreMealByOrigin.jsx
  src/pages/NotFound.jsx
  src/services/APIEndpoints.js
Labels: Code Review

#399 [FEAT & REFACTOR][Context][Implementa contextoe faz refatorações necessárias]
  src/App.js
  src/components/FilterButtons/index.js
  src/components/Menu/index.js
  src/components/RecipeCard/index.js
  src/components/RecipesList/index.js
  src/components/SearchBar/index.js
  src/context/Provider.js
  src/context/RecipesContext.js
  src/context/index.js
  src/pages/Drinks.js
  src/pages/Food.js
  src/redux/actions/index.js
  src/redux/reducers/index.js
  src/services/FoodAPI.js
Labels: Code Review

#374 [GRUPO 3][Requisito 43 ao 46]
  cypress/integration/recipe_detail_spec.js
  src/components/DrinkDetails.js
  src/components/FoodDetails.js
Labels: Code Review

#408 [Group 25] Tela de explorar bebidas ou comidas
  src/components/ExploreDrinksOrFoods/index.js
  src/pages/Explore.jsx
  src/pages/ExploreDrinks.jsx
  src/pages/ExploreFood.jsx
Labels: Code Review

#252 [GRUPO 3][requisito-67-ao-69]
  src/App.js
  src/Pages/DrinkDetails.js
  src/Pages/ExploreDrinkIngredients.js
  src/Pages/ExploreDrinks.js
  src/Pages/ExploreFoodIngredients.js
  src/Pages/ExploreFoods.js
  src/Pages/FoodDetails.js
  src/action/FoodAndDrinkDetailsAction.js
  src/styles/mainScreen.css
Labels: Code Review

#371 Group 30 req32
  .eslintrc.json
  .github/workflows/main.yml
  cypress/integration/recipes_list_spec.js
  cypress/mocks/goatMeals.js
  package-lock.json
  src/App.js
  src/Components/CocktailCards.js
  src/Components/FoodCards.js
  src/Components/ShowCategories.js
  src/Components/styles/Footer.css
  src/Pages/ Explore.js
  src/Pages/Details+css/Details.css
  src/Pages/DrinkDetails.js
  src/Pages/Profile.js
  src/services/ApiRequest.js
Labels: Code Review

#414 subindo novamente a tela de perfil
  src/pages/Profile.jsx
Labels: Code Review

#425 Continuação requisito tela de receitas feitas
  src/pages/ProgressoBebidas.js
  src/pages/ReceitasFeitas.js
Labels: Code Review

#445 [Grupo 12] - Implementação do Carousel
  package-lock.json
  package.json
  src/components/DrinksRecomendations.js
  src/components/MealsRecomendations.js
  src/components/YoutubePlayer.js
  src/pages/meals/MealsDetails.js
Labels: Code Review

#453 [Grupo 2] (SearchBar) Adiciona requisitos 11 a 14
  .eslintrc.json
  package-lock.json
  src/components/Card.js
  src/components/Header.js
  src/components/SearchBar.js
  src/index.js
  src/pages/DrinkByIngredients.js
  src/pages/Drinks.js
  src/pages/ExploreDrink.js
  src/pages/ExploreFood.js
  src/pages/FoodByArea.js
  src/pages/FoodByIngredients.js
  src/pages/Foods.js
  src/pages/Profile.js
  src/redux/actions/index.js
  src/redux/actions/recipes.js
  src/redux/actions/search.js
  src/redux/reducers/index.js
  src/redux/reducers/recipes.js
  src/redux/reducers/search.js
  src/redux/types/index.js
  src/services/api.js
Labels: Code Review

#457 Group 16 requirement 27
  src/Redux/actions/index.js
  src/Redux/reducers/couldRedirect.js
  src/Redux/reducers/filter.js
  src/Redux/reducers/index.js
  src/components/Card.jsx
  src/components/Cards.jsx
  src/components/Filters.jsx
Labels: Code Review

#465 [Grupo 12] - Checkbox In Progress
  src/components/DrinksComponent.js
  src/components/MealsComponent.js
  src/components/SearchBar.js
  src/pages/drinks/DrinksDetails.js
  src/pages/drinks/DrinksInProgress.js
  src/pages/meals/MealsDetails.js
  src/pages/meals/MealsInProgress.js
Labels: Code Review

#464 Group 16 details page requisito 33 to 42
  package-lock.json
  package.json
  src/components/Card.css
  src/components/Card.jsx
  src/components/Cards.css
  src/components/Cards.jsx
  src/components/DetailsDrink.jsx
  src/components/DetailsFood.jsx
  src/pages/Details.jsx
  src/pages/InProgress.jsx
  src/pages/Styles/Details.css
  src/services/fetchRecipes.js
Labels: Code Review

#470 Requisito tela de receitas favoritas com gambiarra
  src/context/AppContext.js
  src/pages/DetalhesBebida.js
  src/pages/DetalhesComida.js
  src/pages/ReceitasFavoritas.js
  src/pages/ReceitasFeitas.js
Labels: Code Review

#442 [FEAT][GROUP28][SEARCHBAR]
  src/components/MainCards.jsx
  src/components/SearchBar.jsx
  src/pages/Drinks.jsx
  src/pages/Foods.jsx
Labels: Code Review

#474 Group 16 correção do merge
  src/components/Card.css
  src/components/Card.jsx
  src/components/Cards.jsx
  src/pages/Details.jsx
  src/pages/Styles/Details.css
  src/services/fetchRecipes.js
Labels: Code Review
